version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.9
    working_directory: ~/my_python_project
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: python -m unittest discover tests

  test1:
    docker:
      - image: cimg/python:3.9
    working_directory: ~/my_python_project
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: python -m unittest tests/test_module1.py

  test2:
    docker:
      - image: cimg/python:3.9
    working_directory: ~/my_python_project
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: python -m unittest tests/test_module2.py

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test1:
          requires:
            - build
      - test2:
          requires:
            - build
