version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.9
    working_directory: ~/my_python_project
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: python -m unittest discover tests

  test1:
    docker:
      - image: cimg/python:3.9
    working_directory: ~/my_python_project
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: python -m unittest tests/test_module1.py

  test2:
    docker:
      - image: cimg/python:3.9
    working_directory: ~/my_python_project
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: python -m unittest tests/test_module2.py

  code_quality:
    docker:
      - image: cimg/python:3.9
    working_directory: ~/my_python_project
    steps:
      - checkout
      - run: pip install flake8
      - run: flake8 .

  deploy:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Deploy Simulation
          command: echo "Deploying Application..."

workflows:
  build_and_test:
    jobs:
      - build
      - test1:
          requires:
            - build
      - test2:
          requires:
            - build

  quality_and_deploy:
    jobs:
      - code_quality
      - deploy:
          requires:
            - code_quality
