version: 2.1

jobs:
  setup:
    docker:
      - image: cimg/python:3.9
    working_directory: ~/my_python_project
    steps:
      - checkout
      - run:
          name: Setup environment
          command: |
            echo "Setting up environment variables and pre-requisites."
            pip install -U pip

  build:
    docker:
      - image: cimg/python:3.9
    working_directory: ~/my_python_project
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run tests
          command: python -m unittest discover tests

  test1:
    docker:
      - image: cimg/python:3.9
    working_directory: ~/my_python_project
    steps:
      - checkout
      - run:
          name: Install dependencies and run specific tests
          command: |
            pip install -r requirements.txt
            python -m unittest tests/test_module1.py

  test2:
    docker:
      - image: cimg/python:3.9
    working_directory: ~/my_python_project
    steps:
      - checkout
      - run:
          name: Install dependencies and run specific tests
          command: |
            pip install -r requirements.txt
            python -m unittest tests/test_module2.py

  cleanup:
    docker:
      - image: cimg/python:3.9
    working_directory: ~/my_python_project
    steps:
      - checkout
      - run:
          name: Cleanup resources
          command: |
            echo "Cleaning up resources and temporary files."

workflows:
  version: 2
  build_and_test:
    jobs:
      - setup
      - build:
          requires:
            - setup
      - test1:
          requires:
            - build
      - test2:
          requires:
            - build
      - cleanup:
          requires:
            - test1
            - test2

  deploy_workflow:
    jobs:
      - setup
      - build:
          requires:
            - setup
      - deploy:
          requires:
            - build
      - cleanup:
          requires:
            - deploy

