version: 2.1

orbs:
  slack: circleci/slack@4.4.2

jobs:
  build:
    docker:
      - image: cimg/python:3.9
    working_directory: ~/my_python_project
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: python -m unittest discover tests

  test1:
    docker:
      - image: cimg/python:3.9
    working_directory: ~/my_python_project
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: python -m unittest tests/test_module1.py

  test2:
    docker:
      - image: cimg/python:3.9
    working_directory: ~/my_python_project
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: python -m unittest tests/test_module2.py

  code_analysis:
    docker:
      - image: cimg/python:3.9
    working_directory: ~/my_python_project
    steps:
      - checkout
      - run: pip install flake8
      - run: flake8 .

  deploy:
    docker:
      - image: cimg/python:3.9
    working_directory: ~/my_python_project
    steps:
      - checkout
      - run:
          name: Deploy Simulation
          command: echo "Deploying Application..."

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - test1:
          requires:
            - build
      - test2:
          requires:
            - build
      - deploy:
          requires:
            - test1
            - test2
      - code_analysis:
          requires:
            - build

  code_quality:
    jobs:
      - build
      - code_analysis:
          requires:
            - build

  notify:
    jobs:
      - deploy
      - code_analysis
    when: always  # This allows the job to run regardless of the success or failure of the workflow.

notify:
  slack/notify:
    event: fail
    mentions: 'YOUR_SLACK_USER_ID'
    template: basic_fail_1
