version: 2.1

orbs:
  slack: circleci/slack@4.4.2

jobs:
  setup:
    docker:
      - image: cimg/python:3.9
    working_directory: ~/my_python_project
    steps:
      - checkout
      - run:
          name: Setup environment
          command: |
            echo "Setting up environment variables and pre-requisites."
            pip install -U pip

  build_and_test:
    docker:
      - image: cimg/python:3.9
    working_directory: ~/my_python_project
    parallelism: 4
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run tests in parallel
          command: |
            circleci tests glob "tests/**/*.py" | circleci tests split --split-by=timings
            python -m unittest

  cleanup:
    docker:
      - image: cimg/python:3.9
    working_directory: ~/my_python_project
    steps:
      - checkout
      - run:
          name: Cleanup resources
          command: |
            echo "Cleaning up resources and temporary files."
      - slack/notify:
          custom: |
            {
              "text": "Cleanup job completed on branch << pipeline.git.branch >>. Check the details on CircleCI!"
            }

  deploy:
    docker:
      - image: cimg/python:3.9
    working_directory: ~/my_python_project
    steps:
      - checkout
      - run:
          name: Deploy Simulation
          command: echo "Deploying Application..."
      - slack/notify:
          custom: |
            {
              "text": "Deployment completed successfully on branch << pipeline.git.branch >>. Ready for production!"
            }

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - setup
      - build_and_test:
          requires:
            - setup
      - cleanup:
          requires:
            - build_and_test
      - deploy:
          requires:
            - build_and_test
