workflows:
  version: 2
  build_test_workflow:
    jobs:
      - setup
      - build_and_test:
          requires:
            - setup
      - cleanup:
          requires:
            - build_and_test
          post-steps:
            - slack/notify:
                on_success: true
                on_fail: true
                channel: '#your-channel-id'
                message: 'Cleanup completed with status: << pipeline.result >>'

  deploy_workflow:
    jobs:
      - setup
      - deploy:
          requires:
            - setup
          post-steps:
            - slack/notify:
                on_success: true
                on_fail: true
                channel: '#your-channel-id'
                message: 'Deployment completed with status: << pipeline.result >>'
      - cleanup:
          requires:
            - deploy
