version: 2.1

jobs:
  setup:
    docker:
      - image: cimg/python:3.9
    working_directory: ~/my_python_project
    steps:
      - checkout
      - run:
          name: Setup environment
          command: |
            echo "Setting up environment variables and pre-requisites."
            pip install -U pip

  build_and_test:
    docker:
      - image: cimg/python:3.9
    working_directory: ~/my_python_project
    parallelism: 4  # Ejecuta este job en 4 contenedores en paralelo
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run tests in parallel
          command: |
            circleci tests glob "tests/**/*.py" | circleci tests split --split-by=timings
            python -m unittest

  cleanup:
    docker:
      - image: cimg/python:3.9
    working_directory: ~/my_python_project
    steps:
      - checkout
      - run:
          name: Cleanup resources
          command: |
            echo "Cleaning up resources and temporary files."

  deploy:
    docker:
      - image: cimg/python:3.9
    working_directory: ~/my_python_project
    steps:
      - checkout
      - run:
          name: Deploy Simulation
          command: echo "Deploying Application..."

workflows:
  version: 2
  build_test_workflow:
    jobs:
      - setup
      - build_and_test:
          requires:
            - setup
      - cleanup:
          requires:
            - build_and_test

  deploy_workflow:
    jobs:
      - setup
      - deploy:
          requires:
            - setup
      - cleanup:
          requires:
            - deploy
