version: 2.1

orbs:
  slack: circleci/slack@4.4.2

jobs:
  setup:
    docker:
      - image: cimg/python:3.9
    working_directory: ~/my_python_project
    steps:
      - checkout
      - run:
          name: Configuración del entorno
          command: |
            echo "Configurando variables de entorno y pre-requisitos."
            pip install -U pip

  build_and_test:
    docker:
      - image: cimg/python:3.9
    working_directory: ~/my_python_project
    parallelism: 4
    steps:
      - checkout
      - run:
          name: Instalación de dependencias
          command: pip install -r requirements.txt
      - run:
          name: Ejecución de pruebas en paralelo
          command: |
            circleci tests glob "tests/**/*.py" | circleci tests split --split-by=timings
            python -m unittest
      - slack/notify:
          event: always
          channel: '$SLACK_DEFAULT_CHANNEL'
          custom: |
            {
              "text": "Pruebas completadas en el branch: << pipeline.git.branch >>. Revisa los resultados en CircleCI."
            }

  deploy:
    docker:
      - image: cimg/python:3.9
    working_directory: ~/my_python_project
    steps:
      - checkout
      - run:
          name: Simulación de despliegue
          command: echo "Desplegando la aplicación..."
      - slack/notify:
          event: always
          channel: '$SLACK_DEFAULT_CHANNEL'
          custom: |
            {
              "text": "Despliegue simulado completado en el branch: << pipeline.git.branch >>."
            }

  cleanup:
    docker:
      - image: cimg/python:3.9
    working_directory: ~/my_python_project
    steps:
      - checkout
      - run:
          name: Limpieza de recursos
          command: |
            echo "Limpiando recursos y archivos temporales."
      - slack/notify:
          event: fail
          channel: '$SLACK_DEFAULT_CHANNEL'
          custom: |
            {
              "text": "Error durante la limpieza de recursos en el branch: << pipeline.git.branch >>. Requiere revisión!"
            }

workflows:
  version: 2
  build_test_cleanup:
    jobs:
      - setup
      - build_and_test:
          requires:
            - setup
      - cleanup:
          requires:
            - build_and_test

  test_deploy_cleanup:
    jobs:
      - setup
      - build_and_test:
          requires:
            - setup
      - deploy:
          requires:
            - build_and_test
      - cleanup:
          requires:
            - deploy
