version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.10.8  # Versión actualizada a una que existe
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Set up Python environment
          command: |
            python -m venv venv
            . venv/bin/activate
      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt
      - run:
          name: Install Flake8 specific version
          command: |
            pip install flake8==7.1.1 mccabe==0.7.0 pycodestyle==2.12.1 pyflakes==3.2.0
      - run:
          name: Check Flake8 version
          command: flake8 --version
      - run:
          name: Run Flake8
          command: flake8 ./tests
      - run:
          name: Run tests
          command: |
            python -m unittest discover -s tests

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
